import { createHash, randomInt } from "node:crypto";

/**
 * Alphabet without characters that get confused when copied by hand: no I, L,
 * O or U. The code is meant to be written on a piece of paper, quickly, and
 * typed back months later (ADR 0009).
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const GROUPS = 5;
const GROUP_LENGTH = 4;

/** 20 characters over a 32-symbol alphabet: 100 bits, generated by the instance. */
export function createRecoveryCode(): string {
  const groups: string[] = [];

  for (let group = 0; group < GROUPS; group++) {
    let chunk = "";

    for (let index = 0; index < GROUP_LENGTH; index++) {
      chunk += ALPHABET[randomInt(ALPHABET.length)];
    }

    groups.push(chunk);
  }

  return groups.join("-");
}

/**
 * Accepts what a person actually types: any casing, any grouping, and the two
 * transcription slips that matter. `O` and `I`/`L` are not in the alphabet, so
 * folding them onto `0` and `1` corrects a misreading without losing entropy.
 * Anything else that does not belong simply fails to match, which is correct.
 */
export function normalizeRecoveryCode(input: string): string {
  return input
    .toUpperCase()
    .replaceAll(/[^0-9A-Z]/gu, "")
    .replaceAll("O", "0")
    .replaceAll(/[IL]/gu, "1");
}

/**
 * A fast hash is right here: the code carries 100 bits of machine-generated
 * entropy, so there is no dictionary to slow down — the same reasoning that
 * separates session tokens from passwords in ADR 0008.
 */
export function hashRecoveryCode(code: string): string {
  return createHash("sha256").update(normalizeRecoveryCode(code), "utf8").digest("hex");
}
