import { createReadableCode, hashCode, normalizeCode } from "./codes.js";

/** Five groups: 100 bits, generated by the instance and never chosen by a person. */
const RECOVERY_GROUPS = 5;

export function createRecoveryCode(): string {
  return createReadableCode(RECOVERY_GROUPS);
}

export function normalizeRecoveryCode(input: string): string {
  return normalizeCode(input);
}

export function hashRecoveryCode(code: string): string {
  return hashCode(code);
}
