import { existsSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

import { loadConfig, type AppConfig } from "@estia/config";
import type { MediaView } from "@estia/contracts";
import { withTempDataDir } from "@estia/testing";
import type { FastifyInstance } from "fastify";
import { describe, expect, it } from "vitest";

import { buildApp } from "../app.js";
import { openDatabase } from "../db/database.js";
import { encodeJpegForTests, encodePngForTests, samplePixels } from "./fixtures.js";

const SETUP_TOKEN = "token-di-prova";
const ADMIN = { password: "una-password-lunga", username: "palu" };

function configFor(dataDir: string, media: Partial<AppConfig["media"]> = {}): AppConfig {
  const base = loadConfig({
    ESTIA_DATA_DIR: dataDir,
    ESTIA_HOST: "127.0.0.1",
    ESTIA_LOG_LEVEL: "silent",
  });

  return { ...base, media: { ...base.media, ...media } };
}

function bearer(token: string): Record<string, string> {
  return { authorization: `Bearer ${token}` };
}

interface Context {
  app: FastifyInstance;
  dataDir: string;
  anna: string;
  marco: string;
  moderator: string;
}

async function withInstance(
  use: (context: Context) => Promise<void>,
  media: Partial<AppConfig["media"]> = {},
): Promise<void> {
  await withTempDataDir(async (dataDir) => {
    const app = await buildApp(configFor(dataDir, media), { setupToken: SETUP_TOKEN });

    try {
      await app.inject({
        method: "POST",
        payload: {
          adminPassword: ADMIN.password,
          adminUsername: ADMIN.username,
          name: "Via Roma",
          setupToken: SETUP_TOKEN,
        },
        url: "/api/v1/instance/setup",
      });

      for (const [username, role] of [
        ["anna", "member"],
        ["marco", "member"],
        ["mod", "instance_moderator"],
      ] as const) {
        await app.identityService.createUser({ password: "password-lunga-ok", role, username });
      }

      const signIn = async (username: string): Promise<string> =>
        (
          await app.inject({
            method: "POST",
            payload: { password: "password-lunga-ok", username },
            url: "/api/v1/auth/login",
          })
        ).json().token;

      await use({
        anna: await signIn("anna"),
        app,
        dataDir,
        marco: await signIn("marco"),
        moderator: await signIn("mod"),
      });
    } finally {
      await app.close();
    }
  });
}

function uploadRaw(app: FastifyInstance, token: string, bytes: Uint8Array, contentType?: string) {
  return app.inject({
    headers: { ...bearer(token), "content-type": contentType ?? "application/octet-stream" },
    method: "POST",
    payload: Buffer.from(bytes),
    url: "/api/v1/media",
  });
}

async function uploadPhoto(
  app: FastifyInstance,
  token: string,
  width = 800,
  height = 600,
): Promise<MediaView> {
  const response = await uploadRaw(
    app,
    token,
    await encodeJpegForTests(samplePixels(width, height)),
  );

  expect(response.statusCode).toBe(201);

  return response.json();
}

function publish(app: FastifyInstance, token: string, body: string, media?: unknown[]) {
  return app.inject({
    headers: bearer(token),
    method: "POST",
    payload: media === undefined ? { body } : { body, media },
    url: "/api/v1/posts",
  });
}

describe("uploading an image", () => {
  it("accepts a photo and answers with its measurements", async () => {
    await withInstance(async ({ app, anna }) => {
      const uploaded = await uploadPhoto(app, anna, 800, 600);

      expect(uploaded).toMatchObject({ height: 600, width: 800 });
      // The thumbnail is generated by the instance, not sent by the client.
      expect(uploaded).toMatchObject({ thumbHeight: 480, thumbWidth: 640 });
    });
  });

  it("is closed to anyone without a live session", async () => {
    await withInstance(async ({ app, anna }) => {
      const bytes = await encodeJpegForTests(samplePixels(64, 64));

      expect(
        (
          await app.inject({
            headers: { "content-type": "application/octet-stream" },
            method: "POST",
            payload: Buffer.from(bytes),
            url: "/api/v1/media",
          })
        ).statusCode,
      ).toBe(401);

      await app.inject({ headers: bearer(anna), method: "POST", url: "/api/v1/auth/logout" });

      expect((await uploadRaw(app, anna, bytes)).statusCode).toBe(401);
    });
  });

  /** ADR 0011, punto 1: the content decides, not what the request says it is. */
  it("refuses a file that says it is an image and is not", async () => {
    await withInstance(async ({ app, anna }) => {
      const disguised = Buffer.from("<?php system($_GET['c']); ?>", "utf8");
      const response = await uploadRaw(app, anna, disguised, "image/jpeg");

      expect(response.statusCode).toBe(415);
      expect(response.json().code).toBe("unsupported_media_type");
    });
  });

  it("refuses an image that would decompress into far too much memory", async () => {
    await withInstance(
      async ({ app, anna }) => {
        // Small file, enormous picture: the pixel limit is a separate defence
        // from the byte limit precisely because of this (ADR 0011, punto 2).
        const bomb = await encodePngForTests(samplePixels(2000, 2000));
        const response = await uploadRaw(app, anna, bomb);

        expect(response.statusCode).toBe(413);
        expect(response.json().code).toBe("media_too_many_pixels");
      },
      { maxPixels: 1_000_000 },
    );
  });

  it("refuses an upload past the byte limit", async () => {
    await withInstance(
      async ({ app, anna }) => {
        const response = await uploadRaw(
          app,
          anna,
          await encodeJpegForTests(samplePixels(900, 900)),
        );

        expect(response.statusCode).toBe(413);
      },
      { maxBytes: 2048 },
    );
  });

  it("applies the quota before writing anything", async () => {
    const photo = await encodeJpegForTests(samplePixels(400, 300));

    // Room for exactly one photo: after the first, the thumbnail alone puts the
    // member over.
    await withInstance(
      async ({ app, anna, dataDir }) => {
        expect((await uploadRaw(app, anna, photo)).statusCode).toBe(201);

        const second = await uploadRaw(app, anna, photo);

        expect(second.statusCode).toBe(413);
        expect(second.json().code).toBe("media_quota_exceeded");

        // Refused before writing: the second upload left nothing behind, so
        // only the first photo and its thumbnail are on disk.
        expect(storedFiles(dataDir)).toHaveLength(2);
      },
      { quotaBytesPerUser: photo.byteLength + 1 },
    );
  });

  it("counts each member's images separately", async () => {
    const photo = await encodeJpegForTests(samplePixels(400, 300));

    await withInstance(
      async ({ app, anna, marco }) => {
        expect((await uploadRaw(app, anna, photo)).statusCode).toBe(201);
        expect((await uploadRaw(app, anna, photo)).statusCode).toBe(413);
        // Anna filling her space must not take Marco's.
        expect((await uploadRaw(app, marco, photo)).statusCode).toBe(201);
      },
      { quotaBytesPerUser: photo.byteLength + 1 },
    );
  });

  it("strips the Exif of an uploaded photo before storing it", async () => {
    await withInstance(async ({ app, anna, dataDir }) => {
      const original = await encodeJpegForTests(samplePixels(300, 200));
      const exif = Buffer.from("Exif\0\0GPS 45.4642 N, 9.1900 E", "utf8");
      const segment = Buffer.alloc(4 + exif.byteLength);

      segment[0] = 0xff;
      segment[1] = 0xe1;
      segment.writeUInt16BE(exif.byteLength + 2, 2);
      exif.copy(segment, 4);

      const tagged = Buffer.concat([original.subarray(0, 2), segment, original.subarray(2)]);
      const uploaded = await uploadRaw(app, anna, tagged);

      expect(uploaded.statusCode).toBe(201);

      const stored = await app.inject({
        headers: bearer(anna),
        method: "GET",
        url: `/api/v1/media/${uploaded.json().id}`,
      });

      expect(stored.rawPayload.includes("45.4642")).toBe(false);
      expect(storedFiles(dataDir).length).toBeGreaterThan(0);
    });
  });
});

describe("reading an image back", () => {
  it("serves the original and the thumbnail to a member", async () => {
    await withInstance(async ({ app, anna, marco }) => {
      const uploaded = await uploadPhoto(app, anna);

      const original = await app.inject({
        headers: bearer(marco),
        method: "GET",
        url: `/api/v1/media/${uploaded.id}`,
      });
      const thumbnail = await app.inject({
        headers: bearer(marco),
        method: "GET",
        url: `/api/v1/media/${uploaded.id}/thumb`,
      });

      expect(original.statusCode).toBe(200);
      expect(original.headers["content-type"]).toBe("image/jpeg");
      expect(thumbnail.statusCode).toBe(200);
      expect(thumbnail.headers["content-type"]).toBe("image/webp");
      // The thumbnail is what the timeline loads, and it is much lighter.
      expect(thumbnail.rawPayload.byteLength).toBeLessThan(original.rawPayload.byteLength);
    });
  });

  /** ADR 0012: knowing an identifier is not a credential. */
  it("refuses to serve an image to anyone without a session", async () => {
    await withInstance(async ({ app, anna }) => {
      const uploaded = await uploadPhoto(app, anna);

      for (const url of [`/api/v1/media/${uploaded.id}`, `/api/v1/media/${uploaded.id}/thumb`]) {
        expect((await app.inject({ method: "GET", url })).statusCode).toBe(401);
      }
    });
  });

  it("stops serving an image to a revoked session", async () => {
    await withInstance(async ({ app, anna, marco }) => {
      const uploaded = await uploadPhoto(app, anna);

      await app.inject({ headers: bearer(marco), method: "POST", url: "/api/v1/auth/logout" });

      expect(
        (
          await app.inject({
            headers: bearer(marco),
            method: "GET",
            url: `/api/v1/media/${uploaded.id}`,
          })
        ).statusCode,
      ).toBe(401);
    });
  });

  it("says plainly when an image is not there", async () => {
    await withInstance(async ({ app, anna }) => {
      const response = await app.inject({
        headers: bearer(anna),
        method: "GET",
        url: "/api/v1/media/non-esiste",
      });

      expect(response.statusCode).toBe(404);
      expect(response.json().code).toBe("media_not_found");
    });
  });

  it("serves media under a policy that forbids interpreting them", async () => {
    await withInstance(async ({ app, anna }) => {
      const uploaded = await uploadPhoto(app, anna);
      const response = await app.inject({
        headers: bearer(anna),
        method: "GET",
        url: `/api/v1/media/${uploaded.id}`,
      });

      expect(response.headers["content-security-policy"]).toBe("default-src 'none'; sandbox");
      expect(response.headers["x-content-type-options"]).toBe("nosniff");
    });
  });
});

describe("images on a post", () => {
  it("travels with the post, in the order it was attached", async () => {
    await withInstance(async ({ app, anna, marco }) => {
      const first = await uploadPhoto(app, anna, 400, 300);
      const second = await uploadPhoto(app, anna, 300, 400);

      const created = await publish(app, anna, "Il mercatino di ieri", [
        { altText: "Banchi in cortile", id: first.id },
        { id: second.id },
      ]);

      expect(created.statusCode).toBe(201);
      expect(created.json().images).toEqual([
        expect.objectContaining({ altText: "Banchi in cortile", height: 300, id: first.id }),
        expect.objectContaining({ altText: "", id: second.id }),
      ]);

      const seenByMarco = (
        await app.inject({ headers: bearer(marco), method: "GET", url: "/api/v1/posts" })
      ).json().posts[0];

      expect(seenByMarco.images.map((image: { id: string }) => image.id)).toEqual([
        first.id,
        second.id,
      ]);
    });
  });

  it("lets a photo be the whole message", async () => {
    await withInstance(async ({ app, anna }) => {
      const photo = await uploadPhoto(app, anna);
      const created = await publish(app, anna, "", [{ id: photo.id }]);

      expect(created.statusCode).toBe(201);
      expect(created.json()).toMatchObject({ body: "" });
      expect(created.json().images).toHaveLength(1);
    });
  });

  it("still refuses a post with neither words nor images", async () => {
    await withInstance(async ({ app, anna }) => {
      expect((await publish(app, anna, "   ")).statusCode).toBe(400);
      expect((await publish(app, anna, "", [])).statusCode).toBe(400);
    });
  });

  it("refuses to let someone attach an image that is not theirs", async () => {
    await withInstance(async ({ app, anna, marco }) => {
      const photo = await uploadPhoto(app, anna);
      const stolen = await publish(app, marco, "Guardate qua", [{ id: photo.id }]);

      expect(stolen.statusCode).toBe(404);

      // The refused post does not exist either: the two are one write.
      expect(
        (await app.inject({ headers: bearer(marco), method: "GET", url: "/api/v1/posts" })).json()
          .posts,
      ).toHaveLength(0);
    });
  });

  it("refuses to use the same image in two posts", async () => {
    await withInstance(async ({ app, anna }) => {
      const photo = await uploadPhoto(app, anna);

      expect((await publish(app, anna, "Prima", [{ id: photo.id }])).statusCode).toBe(201);

      const again = await publish(app, anna, "Ancora", [{ id: photo.id }]);

      expect(again.statusCode).toBe(409);
      expect(again.json().code).toBe("media_already_used");
    });
  });

  it("takes the images away with the body when a moderator hides a post", async () => {
    await withInstance(async ({ app, anna, marco, moderator }) => {
      const photo = await uploadPhoto(app, anna);
      const post = (await publish(app, anna, "Da nascondere", [{ id: photo.id }])).json();

      await app.inject({
        headers: bearer(moderator),
        method: "POST",
        payload: { hidden: true },
        url: `/api/v1/posts/${post.id}/hidden`,
      });

      const timeline = async (token: string) =>
        (await app.inject({ headers: bearer(token), method: "GET", url: "/api/v1/posts" })).json()
          .posts[0];

      // Often the image is exactly what was hidden.
      expect(await timeline(marco)).toMatchObject({ body: "", hidden: true, images: [] });
      expect((await timeline(anna)).images).toHaveLength(1);
    });
  });

  it("frees the files when the post is deleted", async () => {
    await withInstance(async ({ app, anna, dataDir }) => {
      const photo = await uploadPhoto(app, anna);
      const post = (await publish(app, anna, "Poi ci ripenso", [{ id: photo.id }])).json();

      expect(storedFiles(dataDir)).toHaveLength(2);

      const removed = await app.inject({
        headers: bearer(anna),
        method: "DELETE",
        url: `/api/v1/posts/${post.id}`,
      });

      expect(removed.statusCode).toBe(204);
      // The post keeps a tombstone for a future federation; the bytes do not.
      expect(storedFiles(dataDir)).toHaveLength(0);
      expect(
        (
          await app.inject({
            headers: bearer(anna),
            method: "GET",
            url: `/api/v1/media/${photo.id}`,
          })
        ).statusCode,
      ).toBe(404);
    });
  });
});

describe("orphaned uploads", () => {
  it("are collected once they are old, and only then", async () => {
    await withTempDataDir(async (dataDir) => {
      let now = new Date("2026-08-14T10:00:00.000Z");
      const app = await buildApp(configFor(dataDir), {
        now: () => now,
        setupToken: SETUP_TOKEN,
      });

      try {
        await app.inject({
          method: "POST",
          payload: {
            adminPassword: ADMIN.password,
            adminUsername: ADMIN.username,
            name: "Via Roma",
            setupToken: SETUP_TOKEN,
          },
          url: "/api/v1/instance/setup",
        });

        const token = (
          await app.inject({
            method: "POST",
            payload: { password: ADMIN.password, username: ADMIN.username },
            url: "/api/v1/auth/login",
          })
        ).json().token;

        const abandoned = await uploadPhoto(app, token);
        const kept = await uploadPhoto(app, token);

        await publish(app, token, "Questa la pubblico", [{ id: kept.id }]);

        // An hour later nothing is old enough to collect.
        now = new Date("2026-08-14T11:00:00.000Z");
        expect(await app.mediaService.sweepOrphans()).toBe(0);
        expect(storedFiles(dataDir)).toHaveLength(4);

        // Two days later the upload nobody used is gone, and the post's is not.
        now = new Date("2026-08-16T10:00:00.000Z");
        expect(await app.mediaService.sweepOrphans()).toBe(1);
        expect(storedFiles(dataDir)).toHaveLength(2);

        expect(
          (
            await app.inject({
              headers: bearer(token),
              method: "GET",
              url: `/api/v1/media/${abandoned.id}`,
            })
          ).statusCode,
        ).toBe(404);
        expect(
          (
            await app.inject({
              headers: bearer(token),
              method: "GET",
              url: `/api/v1/media/${kept.id}`,
            })
          ).statusCode,
        ).toBe(200);
      } finally {
        await app.close();
      }
    });
  });
});

describe("where the files land", () => {
  it("names them after an identifier the instance generated", async () => {
    await withInstance(async ({ app, anna, dataDir }) => {
      const uploaded = await uploadPhoto(app, anna);
      const files = storedFiles(dataDir);

      // Nothing in the path comes from the upload: the request carried no file
      // name at all, and could not have influenced it if it had
      // (PROJECT_SPEC §9).
      expect(files.sort()).toEqual([`${uploaded.id}.jpeg`, `${uploaded.id}.thumb.webp`].sort());
      expect(existsSync(path.join(dataDir, "media", uploaded.id.slice(0, 2)))).toBe(true);
    });
  });

  /** SECURITY_BASELINE §4: decided, applied by the code, and checked here. */
  it("keeps the photographs unreadable to other users of the same machine", async () => {
    await withInstance(async ({ app, anna, dataDir }) => {
      const uploaded = await uploadPhoto(app, anna);
      const directory = path.join(dataDir, "media", uploaded.id.slice(0, 2));

      expect(statSync(path.join(dataDir, "media")).mode & 0o777).toBe(0o700);
      expect(statSync(directory).mode & 0o777).toBe(0o700);

      for (const file of readdirSync(directory)) {
        expect({ file, mode: statSync(path.join(directory, file)).mode & 0o777 }).toEqual({
          file,
          mode: 0o600,
        });
      }
    });
  });

  it("records the size in the database, which is what the quota reads", async () => {
    await withInstance(async ({ app, anna, dataDir }) => {
      const uploaded = await uploadPhoto(app, anna);

      await app.close();

      const database = openDatabase(dataDir);

      try {
        const row = database
          .prepare("SELECT byte_size, width, height, post_id FROM media WHERE id = ?")
          .get(uploaded.id) as { byte_size: number; width: number; height: number; post_id: null };

        expect(row).toMatchObject({ height: 600, post_id: null, width: 800 });
        // What the answer reported is what the quota will count.
        expect(Number(row.byte_size)).toBe(uploaded.byteSize);
      } finally {
        database.close();
      }
    });
  });
});

/** Every stored file, ignoring the two-character directories they are spread over. */
function storedFiles(dataDir: string): string[] {
  const root = path.join(dataDir, "media");

  if (!existsSync(root)) {
    return [];
  }

  return readdirSync(root, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name);
}
