/**
 * Generated by `pnpm i18n` from the catalogues in `packages/i18n/locales`. Do not edit by hand.
 *
 * Every key of the source language, and the placeholders its sentence takes.
 */
export interface MessageParamMap {
  "auth.login.device_computer": never;
  "auth.login.device_phone": never;
  "auth.login.error_credentials": never;
  "auth.login.error_unreachable": never;
  "auth.login.forgot": never;
  "auth.login.invite": never;
  "auth.login.password": never;
  "auth.login.submit": never;
  "auth.login.submitting": never;
  "auth.login.username": never;
  "common.error.generic": never;
  "common.error.unreachable": never;
  "common.loading": never;
  "common.this_instance": never;
  "common.unreachable.body": never;
  "common.unreachable.title": never;
  "errors.unknown_language": "language";
  "language.automatic": never;
  "language.automatic_note": "language";
  "language.choose": never;
  "language.error_instance": never;
  "language.error_save": never;
  "language.instance": never;
  "language.instance_note": never;
  "language.purpose": never;
  "language.saving": never;
  "language.yours": never;
  "meta.incomplete": "percent";
  "meta.name": never;
  "sections.appearance.note": never;
  "sections.appearance.title": never;
  "sections.back": never;
  "sections.backup.note": never;
  "sections.backup.title": never;
  "sections.chat.note": never;
  "sections.chat.title": never;
  "sections.devices.note": never;
  "sections.devices.title": never;
  "sections.empty_detail": never;
  "sections.estianet.note": never;
  "sections.estianet.title": never;
  "sections.group.admin": never;
  "sections.group.instance": never;
  "sections.group.you": never;
  "sections.info.note": never;
  "sections.info.title": never;
  "sections.invites.note": never;
  "sections.invites.title": never;
  "sections.language.note": never;
  "sections.language.title": never;
  "sections.loading": never;
  "sections.log.note": never;
  "sections.log.title": never;
  "sections.nav_label": never;
  "sections.no_match": never;
  "sections.presence.note": never;
  "sections.presence.title": never;
  "sections.search": never;
  "sections.status.note": never;
  "sections.status.title": never;
  "sections.title": never;
  "time.days": "count";
  "time.hours": "count";
  "time.minutes": "count";
  "time.now": never;
  "time.yesterday": never;
}
