/**
 * Generated by `pnpm i18n` from the catalogues in `packages/i18n/locales`. Do not edit by hand.
 *
 * Every language ESTIA has, the source first, with how much of it is translated (ADR 0044 §4).
 */
import type { LanguageInfo } from "./catalog.js";

export const LANGUAGES: readonly LanguageInfo[] = [
  {
    code: "it",
    name: "Italiano",
    percent: 100,
    incomplete: "In questa versione l'italiano è tradotto solo al {{percent}}%.",
  },
  {
    code: "en",
    name: "English",
    percent: 100,
    incomplete: "In this version, English is only {{percent}}% translated.",
  },
];
