/**
 * The files `pnpm i18n` writes from the catalogues (ADR 0044 §6).
 *
 * Each function returns text and touches nothing: the generator decides where
 * it goes, and the test that keeps the generated files current compares the
 * same text with what is on disk.
 */
import {
  type Catalogue,
  flatten,
  type LanguageInfo,
  languages,
  META_NAMESPACE,
  restrict,
} from "./catalog.js";
import {
  baseKey,
  interpolate,
  placeholdersOf,
  pluralCategoryOf,
  SOURCE_LANGUAGE,
} from "./runtime.js";

const HEADER =
  "Generated by `pnpm i18n` from the catalogues in `packages/i18n/locales`. Do not edit by hand.";

/**
 * The type of every key of the source language, with the placeholders its
 * sentence takes. A plural group always takes `count`, even when a form does
 * not print it: the count is what picks the form.
 */
export function renderKeys(catalogue: Catalogue): string {
  const source = flatten(catalogue[SOURCE_LANGUAGE] ?? {});
  const params = new Map<string, Set<string>>();

  for (const [key, message] of Object.entries(source)) {
    const base = baseKey(key);
    const names = params.get(base) ?? new Set<string>();

    if (pluralCategoryOf(key) !== undefined) {
      names.add("count");
    }

    for (const name of placeholdersOf(message)) {
      names.add(name);
    }

    params.set(base, names);
  }

  const lines = [...params.keys()].sort().map((key) => {
    const names = [...params.get(key)!].sort();
    const type =
      names.length === 0 ? "never" : names.map((name) => JSON.stringify(name)).join(" | ");

    return `  ${JSON.stringify(key)}: ${type};`;
  });

  return [
    `/**`,
    ` * ${HEADER}`,
    ` *`,
    ` * Every key of the source language, and the placeholders its sentence takes.`,
    ` */`,
    `export interface MessageParamMap {`,
    ...lines,
    `}`,
    ``,
  ].join("\n");
}

/** The list of languages with their completeness, for the web client and the server. */
export function renderLanguages(catalogue: Catalogue): string {
  const list = languages(catalogue);

  return [
    `/**`,
    ` * ${HEADER}`,
    ` *`,
    ` * Every language ESTIA has, the source first, with how much of it is translated (ADR 0044 §4).`,
    ` */`,
    `import type { LanguageInfo } from "./catalog.js";`,
    ``,
    `export const LANGUAGES: readonly LanguageInfo[] = ${JSON.stringify(list, null, 2)};`,
    ``,
  ].join("\n");
}

/** Marks the generated part of a shell script. */
export const SHELL_BEGIN = "# i18n:inizio";
export const SHELL_END = "# i18n:fine";

function singleQuoted(text: string): string {
  return `'${text.replaceAll("'", `'\\''`)}'`;
}

/**
 * The sentences of one shell script, as two POSIX functions.
 *
 * `estia_frase LANGUAGE KEY` puts the sentence in `ESTIA_FRASE` and fails when
 * that language does not have it, so the script can walk the fallback chain
 * itself. `estia_completezza LANGUAGE` prints the language's share, for the
 * warning of ADR 0044 §4.
 */
export function renderShell(catalogue: Catalogue, namespaces: readonly string[]): string {
  const list = languages(catalogue);
  const scoped = restrict(catalogue, [...namespaces, META_NAMESPACE]);
  const lines = [
    `${SHELL_BEGIN} — generato da \`pnpm i18n\` da packages/i18n/locales. Non modificare a mano.`,
    `ESTIA_LINGUE=${singleQuoted(list.map((language) => language.code).join(" "))}`,
    ``,
    `# estia_frase LINGUA CHIAVE — mette la frase in ESTIA_FRASE; fallisce se quella lingua non la ha.`,
    `estia_frase() {`,
    `\tcase "$1" in`,
  ];

  for (const language of list) {
    const messages = flatten(scoped[language.code] ?? {});

    lines.push(`\t${language.code})`, `\t\tcase "$2" in`);

    for (const key of Object.keys(messages).sort()) {
      lines.push(`\t\t${key}) ESTIA_FRASE=${singleQuoted(messages[key]!)} ;;`);
    }

    lines.push(`\t\t*) return 1 ;;`, `\t\tesac`, `\t\t;;`);
  }

  lines.push(`\t*) return 1 ;;`, `\tesac`, `}`, ``);
  lines.push(`# estia_completezza LINGUA — quanto e' tradotta, in percentuale (ADR 0044 §4).`);
  lines.push(`estia_completezza() {`, `\tcase "$1" in`);

  for (const language of list) {
    lines.push(`\t${language.code}) printf '%s' ${language.percent} ;;`);
  }

  lines.push(`\t*) printf '%s' 0 ;;`, `\tesac`, `}`, SHELL_END);

  return lines.join("\n");
}

/** Marks the generated table in `docs/TRANSLATIONS.md`. */
export const DOCS_BEGIN = "<!-- i18n:stato -->";
export const DOCS_END = "<!-- /i18n:stato -->";

/** The table of languages in `docs/TRANSLATIONS.md`. */
export function renderDocsTable(list: readonly LanguageInfo[]): string {
  const rows = list.map((language) => {
    const share =
      language.code === SOURCE_LANGUAGE ? `${language.percent}% · source` : `${language.percent}%`;
    const notice =
      language.percent < 100
        ? interpolate(language.code, language.incomplete, { percent: language.percent })
        : "";

    return `| ${language.name} | \`${language.code}\` | ${share} | ${notice} |`;
  });

  return [
    DOCS_BEGIN,
    ``,
    `| Language | Code | Translated | What the installer and the interface say |`,
    `| --- | --- | --- | --- |`,
    ...rows,
    ``,
    DOCS_END,
  ].join("\n");
}

/**
 * Replaces what sits between two markers, markers included. `undefined` when
 * the markers are not there: the file has not been prepared for generation.
 */
export function replaceBetween(
  text: string,
  begin: string,
  end: string,
  replacement: string,
): string | undefined {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end, start);

  if (start === -1 || stop === -1) {
    return undefined;
  }

  // The begin marker may carry a comment after it on the same line.
  return text.slice(0, start) + replacement + text.slice(stop + end.length);
}
